# Site settings
baseurl = "https://caya.casimpan.com/cvu/"
languageCode = "en-US"
title = "CayA Ventures Unit"
theme = "hugo-faq-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

# Menu
SectionPagesMenu = "main"

	[[menu.main]]
		name = "Internal Bank"
		weight = 10
		url = "#bank"
	[[menu.main]]
		name = "Mudboron Veggies"
		weight = 20
		url = "#veggies-mudboron"
	[[menu.main]]
		name = "Cogon Veggies"
		weight = 30
		url = "#veggies-cogon"
	#[[menu.main]]
	#	name = "Payments"
	#	weight = 40
	#	url = "#payments"
	#[[menu.main]]
	#	name = "Privacy"
	#	weight = 50
	#	url = "#privacy"
	#[[menu.main]]
	#	name = "Delivery"
	#	weight = 60
	#	url = "#delivery"

[params]
	
	# Custom styling
	# To customize the styling of this theme, uncomment and edit the following line to point 
	# to your site's css in the assets/ directory. 

	custom_css = ["css/blue.css"]
